### ISSUE TITLE
DuckDuckGPT + BraveGPT + GoogleGPT no longer show on https://greasyfork.org/en/scripts/by-site/*

### ISSUE THREAD

**Issue by adamlui** [greasyfork-org/greasyfork#1279] opened 2024-06-16 11:01 UTC
https://greasyfork.org/en/scripts/459849-duckduckgpt doesn't show on https://greasyfork.org/en/scripts/by-site/duckduckgo.com
https://greasyfork.org/en/scripts/462440-bravegpt doesn't show on https://greasyfork.org/en/scripts/by-site/brave.com
https://greasyfork.org/en/scripts/478597-googlegpt doesn't show on https://greasyfork.org/en/scripts/by-site/google.com

This started happening within the last hour or so, do you know why?

**Comment by adamlui** [comment] 2024-06-16 11:03
How strange, they have re-appeared in the results

**Comment by adamlui** [comment] 2024-06-16 11:39
GoogleGPT disappeared from all https://greasyfork.org/en/scripts/by-site/* again. I made a code update 14mins ago so the bug appears related to that

**Comment by JasonBarnabe** [comment] 2024-06-16 17:59
It may have been caused by a restart on the DB I did a couple days ago. Sometimes this can cause the search function it to fail to correctly process script updates.

I've run a manual task that may fix it.

**Comment by JasonBarnabe** [comment] 2024-06-16 20:01
It appears to still be happening. Any update gets removed from search results until the hourly reindex happens. Not sure why.

**Comment by adamlui** [comment] 2024-06-17 06:02
It wasn't that bad before your manual task it took ~20mins, also I observed on script page from mobile, the "Updated: Now" would wildly jump from 1st column to 2nd column every sec like it was constantly updating, never saw that happen before, is probably the cause

Also if it stays unfixed & updating every hour, that is quite bad because I make updates like every hour all day, so it unfairly penalizes active script authors who continuously improve experience for Greasy Fork users

**Comment by adamlui** [comment] 2024-06-17 20:26
No, it is absolutely reasonable, just not common. For example:

![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/bdc14281-f5c6-4a2a-989e-f9da89a68f8a)

Notice I have two crucial commits lined up for pushing that vastly improve my scripts' UI, but because of this unfair penalty, I am now waiting until re-index time, thus also deterring further improvements that benefit users since I will not be drafting any more commits such that 'History' gives an accurate overview for users to inspect specific changes and roll back if needed vs. pushing it all at once destroying the benefit of History

**Comment by adamlui** [comment] 2024-06-17 20:34
I could care less if you were to change your Last Updated to be hourly refreshed to prove your accusation is unfounded, but it is critical my updates which my supporters demand at high speed (and even pay me for)...


![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/02050fe9-bb25-4c1a-8a7d-b228d9a65506)
![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/14bb5a3a-58e8-4bec-84af-6bd847e180c3)
![image](https://github.com/greasyfork-org/greasyfork/assets/10906554/e17251cf-348b-44f2-8a0c-f9ace84cfaca)

... are met thru no obstacle outside my control. We just have differing standards on what comprises user satisfaction (for me it is speed, my GitHub commit activity reveals this).

So if you someday fix this bug, then implement the no bumps until every hour, you will see, even without the bumps, my commits will stay fast and furious for this purpose of satisfying user experience I highly prioritize, therefore it is impossible I'm abusing some rule I haven't heard of, just satisfying user demand ASAP that got me where I am today

**Comment by adamlui** [comment] 2024-06-17 20:36
There are actual abusers who make updates that change nothing but version number though, go after them, don't worry about some guy that is bringing heavy traffic to Greasy Fork with awesome userscripts and links to it as the de facto site for AI goodness everywhere he posts

**Comment by adamlui** [comment] 2024-06-17 20:47
Also if you inspect the actual author update frequency, it's commonly every few days to months. Why would a Greasy Fork schemer need to multi-bump per hour to stay on top? Your accusation makes no sense...

**Comment by adamlui** [comment] 2024-06-17 20:59
Also I was serious about buying the site just lemme know when you tire of it

**Comment by adamlui** [comment] 2024-06-17 21:09
> That is where I'm already healthy by daily installs (I'm #2 and #3 for OpenAi for months I don't need bumping

Actually I lost my #3 spot due to this glitch, it kept makign it disappear such that a #4 script that didtn' get updated in nearly a month took the place of one that was getting updated with new APIs and UI features to make AI more awesome to users that they remember to come back to GF for more AI goodies

**Comment by JasonBarnabe** [comment] 2024-06-17 21:10
I was referring specifically to your claim of

> multiple updates like every hour all day

but looking at your script history, this is not what you're doing.

But this not relevant to the issue at hand, so let's keep this issue on-topic.

**Comment by adamlui** [comment] 2024-06-17 21:12
Ok, I am happy to know you have confirmed I am not an abuser and very eager for a fix to bring GF more revenue

**Comment by JasonBarnabe** [comment] 2024-06-17 21:47
This is supposed to be instantaneously updated with [ts-sidekiq-delta](https://github.com/pat/ts-sidekiq-delta) but something broke with that.

Until I can find the problem, I've put in a workaround - it will reindex every five minutes, so that's the maximum amount of time after an update that a script will be missing from results.

**Comment by JasonBarnabe** [comment] 2024-06-18 18:18
I believe this is fixed now. The problem was that ts-sidekiq-delta uses a redis-based lock to avoid concurrent runs, and at some point this was set and not cleared (probably due to a server reboot), preventing further processing. I've cleared the lock and also created https://github.com/pat/ts-sidekiq-delta/pull/14 to add a TTL prevent the problem from reoccurring.

**Closed by JasonBarnabe** 2024-06-18 18:18 UTC
